name: Deploy Function App

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'azure_function/**'
      - 'aggregator.py'
      - '.github/workflows/deploy-function.yml'

env:
  AZURE_FUNCTIONAPP_NAME: unified-feed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: ./azure_function
