name: Deploy Web App

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'unified_feed_app.py'
      - 'templates/**'
      - 'aggregator.py'
      - 'requirements.txt'
      - '.github/workflows/deploy-webapp.yml'

env:
  AZURE_WEBAPP_NAME: ai-feed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create deployment package
        run: |
          zip -r webapp_package.zip unified_feed_app.py templates aggregator.py requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: webapp_package.zip
